-- Generated by scripts/generate_attraction_insert_sql.py
-- Review before running on dev or EC2 database.

-- replace

-- insert attraction
INSERT INTO attraction (
    attraction_name,
    description,
    category_id,
    address,
    transport,
    latitude,
    longitude,
    is_active
) VALUES (
    '彩虹起跑線',
    '2020年9月，臺北市第二道炫目的彩虹地景「彩虹起跑線」在臺北市東區誕生了！位於臺北市政府前市民廣場。

此處彩虹地景由市府延伸至議會方向，類似跑道的形式上巧妙劃了一條線，就像是奔往幸福的起點般，不僅再次傳達臺北市提倡性平的初心，更呼應每年在市府前起走的臺灣同志大遊行。彩虹地景彷彿凝聚著所有人的期待與熱情，讓大家在市府前踩著堅定的步伐，穩穩地朝著幸福之路前進。

(資料來源：臺北市政府觀光傳播局)',
    1,
    '110 臺北市信義區市府路1號 (臺北市政府前市民廣場)',
    '捷運站名：板南線市府站2號出口，走基隆路再走市府路即可到達.松智路站：277、46、266副、699、28、537、博愛公車。松壽路站：665、20、284、647、650、202、621、611、612、266、28、281、245。市府路站：245、261、311、202、263、270、266、651、281、28、537、612。捷運接駁：藍5，於「市政府站」下車；藍7，於「捷運市政府站」下車。',
    25.037697167430807,
    121.56339370393275,
    TRUE
);

SET @new_attraction_id = LAST_INSERT_ID();

INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/191906');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/191907');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/191908');

INSERT INTO attraction_mrt (attraction_id, mrt_id)
VALUES (@new_attraction_id, 32);


-- add

-- insert attraction
INSERT INTO attraction (
    attraction_name,
    description,
    category_id,
    address,
    transport,
    latitude,
    longitude,
    is_active
) VALUES (
    '硫磺谷_大磺嘴',
    '陽明山國家公園硫磺谷地熱景觀區，周圍擁有豐富的火成岩及沉積岩地質環境，周邊還有許多景點，如龍鳳谷、磺溪溫泉步道等，走累了、玩累了還可以前往泡腳池休息，因為溫泉屬酸性硫酸鹽泉，受地底熱作用，含有豐富的硫化物等磺物質，水質呈黃白色、有硫磺味，俗稱「白磺」，泉溫40~60℃，pH值則介於3.2至4.6間，是一處非常適合全家大小一起來享受的好地方。

【硫磺谷泡腳池園區】
園區位址：臺北市北投區泉源路77號對面硫磺谷地熱景觀區內
營運時間：每週二至週日，8時-18時止

(資料來源：臺北市政府產業發展局)',
    7,
    '112 臺北市北投區泉源路',
    '捷運站名：北投捷運站搭乘小7、小9、小26公車於「彌陀寺站」下車。',
    25.14358,
    121.52119,
    TRUE
);

SET @new_attraction_id = LAST_INSERT_ID();

INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215808');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215809');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215810');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215811');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215802');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215803');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215804');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215805');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215806');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/215807');

INSERT INTO attraction_mrt (attraction_id, mrt_id)
VALUES (@new_attraction_id, 5);


-- insert attraction
INSERT INTO attraction (
    attraction_name,
    description,
    category_id,
    address,
    transport,
    latitude,
    longitude,
    is_active
) VALUES (
    '陽明山溫泉區_小油坑',
    '小油坑為一處後火山活動地質景觀區，由陽金公路的小觀音站右轉可達觀景步道，以「後火山作用」所形成之噴氣孔、硫磺結晶、溫泉及壯觀的崩塌地形最具特色。

而在這裡的眺望平台還可遠眺竹子山、大屯山、七星山與小觀音山等火山錐體，以及金山海岸、停車場等。喜歡觀察植物的遊客，還可以用十幾分鐘的時間，一遊附近的箭竹林步道，觀察箭竹林、芒草原和火山植物。&nbsp;',
    7,
    '112 臺北市北投區竹子湖路69號',
    '捷運站名：劍潭捷運站搭乘紅5公車至陽明山站，轉搭108公車至小油坑服務站下車。',
    25.17669,
    121.54683,
    TRUE
);

SET @new_attraction_id = LAST_INSERT_ID();

INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/63396');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/179910');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/179911');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/179912');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/179913');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/179914');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/63393');
INSERT INTO image_url (attraction_id, url)
VALUES (@new_attraction_id, 'https://www.travel.taipei/image/63395');

INSERT INTO attraction_mrt (attraction_id, mrt_id)
VALUES (@new_attraction_id, 31);

