-- Generated by scripts/generate_attraction_update_sql.py
-- Review before running on dev or EC2 database.

-- matched

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63649'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63651'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63655'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63656'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175546'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175547'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/181471'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/181472'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/181473'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/181474'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/181475'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63630'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63644'
FROM attraction
WHERE attraction_name = '二二八和平公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63648'
FROM attraction
WHERE attraction_name = '二二八和平公園';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '北投公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/174759'
FROM attraction
WHERE attraction_name = '北投公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/174760'
FROM attraction
WHERE attraction_name = '北投公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/174761'
FROM attraction
WHERE attraction_name = '北投公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/174762'
FROM attraction
WHERE attraction_name = '北投公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/174763'
FROM attraction
WHERE attraction_name = '北投公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/174758'
FROM attraction
WHERE attraction_name = '北投公園';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '北投文物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63822'
FROM attraction
WHERE attraction_name = '北投文物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63823'
FROM attraction
WHERE attraction_name = '北投文物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63824'
FROM attraction
WHERE attraction_name = '北投文物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63826'
FROM attraction
WHERE attraction_name = '北投文物館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222580'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222581'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222582'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222583'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222584'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222575'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222576'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222577'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222578'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222579'
FROM attraction
WHERE attraction_name = '北投溫泉博物館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '台北101';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64607'
FROM attraction
WHERE attraction_name = '台北101';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182759'
FROM attraction
WHERE attraction_name = '台北101';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182852'
FROM attraction
WHERE attraction_name = '台北101';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '台北當代藝術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63661'
FROM attraction
WHERE attraction_name = '台北當代藝術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63662'
FROM attraction
WHERE attraction_name = '台北當代藝術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63663'
FROM attraction
WHERE attraction_name = '台北當代藝術館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182535'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182536'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182537'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182538'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182539'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182540'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182542'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182543'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182544'
FROM attraction
WHERE attraction_name = '台北霞海城隍廟';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221733'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221734'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221735'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221736'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221737'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221738'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221739'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221740'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221731'
FROM attraction
WHERE attraction_name = '國立故宮博物院';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221732'
FROM attraction
WHERE attraction_name = '國立故宮博物院';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '國立歷史博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/562210'
FROM attraction
WHERE attraction_name = '國立歷史博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/562213'
FROM attraction
WHERE attraction_name = '國立歷史博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/562214'
FROM attraction
WHERE attraction_name = '國立歷史博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/562217'
FROM attraction
WHERE attraction_name = '國立歷史博物館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '國立臺灣科學教育館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63496'
FROM attraction
WHERE attraction_name = '國立臺灣科學教育館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222058'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222049'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222050'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222051'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222052'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222053'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222054'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222055'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222056'
FROM attraction
WHERE attraction_name = '大安森林公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222057'
FROM attraction
WHERE attraction_name = '大安森林公園';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221996'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221988'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221989'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221990'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221991'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221992'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221993'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221994'
FROM attraction
WHERE attraction_name = '大湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221995'
FROM attraction
WHERE attraction_name = '大湖公園';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '大龍峒保安宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63868'
FROM attraction
WHERE attraction_name = '大龍峒保安宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63869'
FROM attraction
WHERE attraction_name = '大龍峒保安宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63871'
FROM attraction
WHERE attraction_name = '大龍峒保安宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63875'
FROM attraction
WHERE attraction_name = '大龍峒保安宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63880'
FROM attraction
WHERE attraction_name = '大龍峒保安宮';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468072'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468063'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468064'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468065'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468066'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468067'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468068'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468069'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468070'
FROM attraction
WHERE attraction_name = '指南宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468071'
FROM attraction
WHERE attraction_name = '指南宮';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179307'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179308'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179309'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179310'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/103329'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179273'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179299'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179300'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179301'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179302'
FROM attraction
WHERE attraction_name = '松山慈祐宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179306'
FROM attraction
WHERE attraction_name = '松山慈祐宮';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '松山文創園區';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179257'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179258'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179260'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179261'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179263'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179264'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179265'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179267'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179268'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179269'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179270'
FROM attraction
WHERE attraction_name = '碧湖公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/179271'
FROM attraction
WHERE attraction_name = '碧湖公園';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '社子島環島與二重疏洪道自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63343'
FROM attraction
WHERE attraction_name = '社子島環島與二重疏洪道自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63342'
FROM attraction
WHERE attraction_name = '社子島環島與二重疏洪道自行車道';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '臺北市立動物園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/361246'
FROM attraction
WHERE attraction_name = '臺北市立動物園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/361247'
FROM attraction
WHERE attraction_name = '臺北市立動物園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64566'
FROM attraction
WHERE attraction_name = '臺北市立動物園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64567'
FROM attraction
WHERE attraction_name = '臺北市立動物園';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175616'
FROM attraction
WHERE attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175617'
FROM attraction
WHERE attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175618'
FROM attraction
WHERE attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175619'
FROM attraction
WHERE attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175620'
FROM attraction
WHERE attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175621'
FROM attraction
WHERE attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175623'
FROM attraction
WHERE attraction_name = '臺北市立美術館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/175047'
FROM attraction
WHERE attraction_name = '臺北市立美術館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468018'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468019'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468020'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468021'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63935'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468007'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468010'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468011'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468015'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468016'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/468017'
FROM attraction
WHERE attraction_name = '艋舺龍山寺';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '華中河濱公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64732'
FROM attraction
WHERE attraction_name = '華中河濱公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64734'
FROM attraction
WHERE attraction_name = '華中河濱公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64735'
FROM attraction
WHERE attraction_name = '華中河濱公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64731'
FROM attraction
WHERE attraction_name = '華中河濱公園';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325920'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325921'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325922'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325923'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325924'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325925'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325926'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325927'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325928'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/325929'
FROM attraction
WHERE attraction_name = '華山1914文化創意產業園區';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292768'
FROM attraction
WHERE attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292769'
FROM attraction
WHERE attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292770'
FROM attraction
WHERE attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292763'
FROM attraction
WHERE attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292764'
FROM attraction
WHERE attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292765'
FROM attraction
WHERE attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292766'
FROM attraction
WHERE attraction_name = '行天宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292767'
FROM attraction
WHERE attraction_name = '行天宮';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '袖珍博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/192688'
FROM attraction
WHERE attraction_name = '袖珍博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/192689'
FROM attraction
WHERE attraction_name = '袖珍博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/192690'
FROM attraction
WHERE attraction_name = '袖珍博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/192691'
FROM attraction
WHERE attraction_name = '袖珍博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/192695'
FROM attraction
WHERE attraction_name = '袖珍博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/192696'
FROM attraction
WHERE attraction_name = '袖珍博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/192687'
FROM attraction
WHERE attraction_name = '袖珍博物館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293072'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293073'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293074'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293075'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293076'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293068'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293069'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293070'
FROM attraction
WHERE attraction_name = '西門紅樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/293071'
FROM attraction
WHERE attraction_name = '西門紅樓';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '長榮海事博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/107067'
FROM attraction
WHERE attraction_name = '長榮海事博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/126702'
FROM attraction
WHERE attraction_name = '長榮海事博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/107058'
FROM attraction
WHERE attraction_name = '長榮海事博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/107060'
FROM attraction
WHERE attraction_name = '長榮海事博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/107064'
FROM attraction
WHERE attraction_name = '長榮海事博物館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/107065'
FROM attraction
WHERE attraction_name = '長榮海事博物館';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214231'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214220'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214221'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214222'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214223'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214224'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214225'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214226'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214227'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214228'
FROM attraction
WHERE attraction_name = '陽明山中山樓';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214230'
FROM attraction
WHERE attraction_name = '陽明山中山樓';

DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/173845'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/173847'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/183001'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/183004'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/183005'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/183006'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/183008'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/183009'
FROM attraction
WHERE attraction_name = '陽明山國家公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/183011'
FROM attraction
WHERE attraction_name = '陽明山國家公園';

-- rename_and_update

UPDATE attraction
SET attraction_name = '七星山系_天母古道親山步道', description = '天母古道親山步道不僅是台北市民熱愛的健行路線，更是一條承載著百年歷史的時光廊道。步道橫跨士林華岡地區的西北山坡，也是紗帽山南邊的鞍部，前身是早年連結金山與天母的「魚路古道」後段。在仰德大道開通後，這條昔日的經濟要道才漸漸沉寂，轉變為今日遊人如織的親山步道。


天母古道生態景觀
天母古道最珍貴的資產，在於其獨特的「壓縮型生態系」。雖然全區海拔僅介於120至300公尺，本應是單純的亞熱帶闊葉林環境，但這裡卻並存著多種不同氣候帶的森林特徵。這一切的關鍵，在於受到大屯山鞍部強勁東北季風的直接影響。季風直撲的迎風面，因強風、多雨與低溫而呈現出涼爽的暖溫帶景致；然而，只要轉入避風的潮濕溪谷中，陰溼的環境反而孕育了熱帶闊葉樹種，因此能觀察到板根、幹生花與纏勒等現象。這種在低海拔地區罕見地匯集了熱帶、亞熱帶與暖溫帶生態的壓縮現象，使天母古道成為一座極為珍貴的戶外自然教室。

◎特別提醒山友：步道下切翠峰瀑布的岔路附近，容易看見猴群出沒，當您看見猴群出現時，請不要任意餵食，以免猴兒為爭搶食物，不小心傷害到您喔！

水管路步道
這條水管路步道可追溯至日治時期。當時為了將第三水源地的泉水接引至天母與士林地區，而特別闢建了這條輸送路線。由於此地自那時起便被劃為保安林區的水源重地，受到了嚴格保護，因此保留下極為原始豐富的森林樣貌，沿途隨處可見依水而生的蕨類、姑婆芋等茂盛植物。

這條步道的結構也相當獨特：在步道前段的爬坡路上，並不會看見水管；直到進入後段的平緩山徑時，巨大的水管其實就埋設在步道正下方。大約在1930年間，為了保護管線，人們開始在水管上方鋪設石板和水泥，這條便於行走的「水管路」便因此形成。直到山勢漸緩、接近天母地區時，水管的路線才與步道分開。而現今位於步道入口處的三角埔發電廠，正是這條步道的起點，在歷史上，它同時也是這條水管輸送系統的終點。


入山林前先暖身
從登山口出發，山友首先要面對的，是一場超過千級石階的嚴峻考驗。這段路被許多人視為進入山林前的最佳「暖身」。步道初期，首先映入眼簾的是一片高大的龍眼樹林，其中有些樹幹粗壯到需要兩人才能合抱，悄悄訴說著此地曾以龍眼為主要產業的過往。隨著高度攀升，傳說中的黑色大水管將會現身，而山路也會隨之變得更加陡直。

這段連續上坡路無可避免地會消耗體力，所幸在中途和石階的盡頭都設有涼亭，供人歇腳喘息。站在中途的涼亭旁回望，天母市區已在山腳下展開，讓人頓時小有成就感。若在天氣晴朗時登頂，更能遠眺林口台地，據說這裡也是欣賞台北夜景的絕佳地點。

當您走完這段漫長的陡坡，抵達終點的蓄水池旁時，不妨在此洗把臉、擦擦汗，因為接下來，馬上就要進入天母古道最精華、也最舒適涼爽的林蔭坦途了。


詩意的步道之旅
造訪過水管路步道的人，多半都會愛上這段路。這裡的路面平整、有如履平地，加上全程都有濃密的林蔭遮蔽，即使在炎炎夏日行走其間也倍感涼爽；到了冬季，雖然能聽見東北季風在溪谷間呼嘯，但步道本身卻不受刺骨寒風侵擾。平坦的路況讓人能放鬆駐足，欣賞沿途景致的變化：視野從遠眺天母、北投的城市風光，漸漸轉為欣賞山林溪谷、梯田與雲霧繚繞的詩意美景。

這條步道之所以能保有如此豐富的生態，要歸功於它自日治時代起就被劃為「水源重地」與「保安林區」的歷史。儘管海拔僅約300公尺，卻因受到良好保護而維持著原始林相，孕育了超過三百種植物，沿途隨處可見依水而生的茂密蕨類與姑婆芋。

豐富的水源是這裡的生態命脈。路旁山崖上可見早期的石頭堆砌，將岩壁滲出的山泉水導入圳溝，吸引了許多溪蝦與蝌蚪聚集。步道後段也有一條清澈的小水溝，同樣源於山泉，是沼蝦、螃蟹、蜻蜓及多種蛙類的繁殖天堂。從秋季到隔年春天，林間時常能聽見斯文豪氏赤蛙那宛如鳥叫般的清脆鳴聲；若是在清晨或黃昏時段造訪，更有機會一睹台灣獼猴在此出沒的珍貴畫面。

&nbsp;', is_active = TRUE
WHERE attraction_name = '七星山系-天母古道親山步道';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221111'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221112'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221113'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221114'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221115'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221106'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221107'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221108'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221109'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221110'
FROM attraction
WHERE attraction_name = '七星山系_天母古道親山步道';

UPDATE attraction
SET attraction_name = '國立中正紀念堂', description = '中正紀念堂是為了紀念中華民國第一任總統蔣介石，他於1975年逝世，次年行政院就破土開建中正紀念堂，設計師是設計圓山大飯店的楊卓成。

紀念堂原址是陸軍總部，當時是臺北市區內最大的軍區，據說從大陸運過來的黃金，就曾經存放在這個地方。紀念堂採用的藍白兩色，是國旗上面主要的顏色，紀念堂頂部天穹的裝飾是青天白日12道光芒，銅像朝西面對總統府和中國大陸，其中都有特殊的意義。隨著民主演進思想開放，紀念堂前的廣場已成了民主運動的集會場。

位於中正紀念堂左右兩側的國家音樂廳與國家戲劇院。戲劇院為戲劇、舞蹈等表演活動的場地，經常舉辦大型的表演活動，包括京劇、戲劇、兒童節目等；音樂廳是臺灣最具水準的音樂展演空間，經常舉辦室內樂，交響樂等大型的音樂活動。而兩廳院前廣場也會不定時舉辦戲劇、音樂活動，吸引眾多遊客前往欣賞。

白牆藍瓦，70公尺高聳立在紀念公園的中央，不論從哪個角度看過去，都很宏偉。國外觀光客來到臺灣，不論行程如何排，都一定會到這裡來參觀一下。紀念堂的下方有陳列和展覽，也有紀念品販售。', is_active = TRUE
WHERE attraction_name = '中正紀念堂';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222951'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222952'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222953'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222954'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222955'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222956'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222957'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222958'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222959'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222960'
FROM attraction
WHERE attraction_name = '國立中正紀念堂';

UPDATE attraction
SET attraction_name = '竹柏參道', description = '位於臺北市文山區，除了聞名的指南宮外，還有一條低調卻令人流連忘返的步道「竹柏參道」。這條步道沿途被竹柏林包圍，綠蔭遮天，環境靜謐幽深，不僅是登山健行的好選擇，也是一處遠離都市喧囂的世外桃源。
竹柏參道的名稱來自於兩側茂密生長的「竹柏」，這是一種常綠喬木，葉片細長如竹，卻帶有柏樹的特性，因此得名。沿途樹影搖曳，四季常青，無論是晨間的陽光灑落還是雨後的霧氣繚繞，都為步道增添了一份詩意與靜謐氛圍。

步道沿途可見一些歷史遺跡，如石燈籠與古老的石亭，見證了這條道路百年來的變遷。參道鋪設平整，坡度適中，適合各個年齡層的遊客步行，步道中段有幾處休憩平台，可供遊客短暫休憩，靜靜感受山林間的蟲鳴鳥叫。

參道兩側設置夜間光環境，以柔和、自然的燈光設計營造寧靜且富有禪意的氛圍，兼顧行走安全與視覺美感，使夜間步行更具沉浸感與儀式感。

竹柏參道一年四季皆適合造訪，夏季有濃密樹蔭遮擋烈日，冬季則少見寒風刺骨的情況。步道沿線無商家，建議攜帶足夠的飲水與輕食補給。若計畫長距離健行，可搭配指南宮或貓空的茶館作為終點，品味當地特色茶點，為旅程畫下完美句點。', is_active = TRUE
WHERE attraction_name = '二格山系-指南宮貓空親山步道';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '竹柏參道';

UPDATE attraction
SET attraction_name = 'SPOT光點台北電影館', description = '佇立在台北中山北路的綠蔭大道旁，一棟典雅的白色二層樓西洋建築格外引人注目。它擁有對稱的希臘式廊柱與寬闊的迴廊，散發著美國南方殖民風格的莊重與悠閒。這棟建築在歷史上曾有著顯赫的外交身分，長期作為美國駐台大使的官邸，包括藍欽、莊萊德、柯爾克等多位大使均曾居住於此。然而，隨著1979年外交情勢轉變，最後一任大使離台，這座美麗的建築也隨之正式關閉，陷入了長時間的沉寂。

這棟閒置多時的老宅，終於在1997年迎來了新的轉機。它被內政部指定為國家三級古蹟，其歷史與建築價值獲得了肯定。臺北市文化局決定為這座空間注入新生命，委託臺灣電影文化協會接手經營，將其活化轉型為以電影文化為核心的藝文空間&mdash;&mdash;「臺北之家」。

如今的「臺北之家」，已是文青與電影愛好者的聖地。老宅的核心是「光點電影院」，一座僅有88個座位的精緻影廳，專門放映藝術及獨立電影。宅邸內的空間也被巧妙運用：「光點．紅氣球」是提供輕食的電影沙龍；「光點．珈琲時光」則座落在庭園的老樹旁，是享受午後悠閒的絕佳角落。知識的渴求能在「光點．生活」書店中被滿足，這是一家專注於「電影」與「城市」主題的書店。此外，建築的迴廊被規劃為藝術展覽館，而多功能藝文廳則提供了演講、座談的空間，並設有電影相關藏書供民眾閱讀。臺北光點，成功地為這座城市的電影文化，點亮了一盞溫暖而美好的光影。', is_active = TRUE
WHERE attraction_name = '光點臺北';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = 'SPOT光點台北電影館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63724'
FROM attraction
WHERE attraction_name = 'SPOT光點台北電影館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63725'
FROM attraction
WHERE attraction_name = 'SPOT光點台北電影館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63727'
FROM attraction
WHERE attraction_name = 'SPOT光點台北電影館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63729'
FROM attraction
WHERE attraction_name = 'SPOT光點台北電影館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63721'
FROM attraction
WHERE attraction_name = 'SPOT光點台北電影館';

UPDATE attraction
SET attraction_name = '內溝溪生態步道', description = '內溝溪為基隆河支流，全長約5.5公里，流域面積約7平方公里。以內溝溪為界以西為臺北市，以東為新北市，為東湖地區民眾散步、休憩、話家常的好去處，同時亦為東湖地區接近自然的最佳場所。

自民國102年開始在東湖內溝溪中游段進行整體景觀改造，並從上游延續將近長約1公里的親水步道，藉由景觀橋與水岸步道之設置，串聯原先被內溝溪所分隔於左右兩岸之臺北與新北兩市之漫遊路徑，清除淤積土壤的同時，恢復五分埤水域環境，營造不同深度之生態棲息環境，打造不分日夜皆可親山、親水、親自然並創造可停留體驗之生態教育空間；以提升居民親近使用之意願，進而認知、了解與共同保育，亦可讓原本存在當地耆老腦海中的美好回憶，得以再次重現。

四大面向
1.具獨特創意及恢復昔日地方自然/人文生活環境
於整體工程結構與造型上儘量採以輕量化為主，融入地方期望之江南園林山水風貌為主，擇以既有環境色彩色系為佳，以尊重與融入內溝溪自然環境，於考量水利、排洪之工程結構上兼具造型美感。

2.保留在地已逐步營造之水岸綠廊及增加堤頂綠化契機
在堤頂防洪機能考量之下，於堤頂有腹地之處進行綠化，豐富水岸生態的營造及綠意蔓延與滋長。

3.水岸棲地保留與改善
以堤岸安全優先，但仍重視於自然生態面向的保留與改善，在整體設計上順應既有護岸坡度、地形，除清淤工程外，不過度挖掘及擾動生態。

4.節能減碳、永續發展
考量節能減碳需求，沿線水岸照明採低度照明為主，保留夜間民眾散步之安全照明，並於串接兩市之重點景觀橋以點燈形式規劃，形塑水岸繁星點點之意象。

(部分資料來源：臺北市政府工務局水利工程處)', is_active = TRUE
WHERE attraction_name = '內溝溪景觀生態步道';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/98306'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/162923'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/162924'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/162925'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/98301'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/98302'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/98304'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/98305'
FROM attraction
WHERE attraction_name = '內溝溪生態步道';

UPDATE attraction
SET attraction_name = '陽明山國家公園_冷水坑', description = '冷水坑坐落於七星山與七股山之間的幽靜谷地，此處曾是火山爆裂口，歲月侵蝕與人為開墾使其樣貌變得柔和，如今僅留下淺淺的凹谷輪廓。地質上主要由凝灰石角礫岩與安山岩構成，泉源附近的岩石因地熱換質，多已呈黏土化，見證火山活動的歷史軌跡。

冷水坑泉水溫度約攝氏40度，遠低於其它溫泉區水溫因而得名。這裡更是台灣唯一的沉澱硫磺礦床，泉水因富含礦物質而呈現夢幻的乳白色，因而獲得「牛奶池」的美名。此處溫泉為地下水間接加熱而成，同時擁有中性碳酸氫鹽泉與弱酸性硫酸鹽泉兩種泉質，獨具特色。

除了享受溫泉，不妨漫步至秀麗的涓絲瀑布，或探訪靜謐的夢幻湖生態保護區。在這片豐饒的環境中，隨時可能與大自然的朋友不期而遇，例如聒噪的長腳赤蛙、叫聲宛如鳥鳴的斯文豪氏赤蛙，或是皮膚佈滿疣粒、外貌樸拙的盤古蟾蜍，偶爾也能瞥見蛇類與爬蟲類的身影。在注意自身安全的同時，也請溫柔地對待這些可愛的住民，靜靜觀察，不驚擾牠們的生活。', is_active = TRUE
WHERE attraction_name = '冷水坑溫泉區';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '陽明山國家公園_冷水坑';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63378'
FROM attraction
WHERE attraction_name = '陽明山國家公園_冷水坑';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63380'
FROM attraction
WHERE attraction_name = '陽明山國家公園_冷水坑';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63389'
FROM attraction
WHERE attraction_name = '陽明山國家公園_冷水坑';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63391'
FROM attraction
WHERE attraction_name = '陽明山國家公園_冷水坑';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63370'
FROM attraction
WHERE attraction_name = '陽明山國家公園_冷水坑';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63375'
FROM attraction
WHERE attraction_name = '陽明山國家公園_冷水坑';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63377'
FROM attraction
WHERE attraction_name = '陽明山國家公園_冷水坑';

UPDATE attraction
SET attraction_name = '臺北市立圖書館北投分館', description = '臺北市立圖書館北投分館是臺灣首座綠建築圖書館，座落於林木茂密、生態環境豐富的北投公園內，與溫泉博物館比鄰而居，地下一層、地上二層，總面積650坪的圖書館。室內書香，戶外鳥語，相映成趣，閱讀成了一件愜意、享受的活動。

館內藏書達上萬冊，並以「生態保育」為館藏特色，琳瑯滿目的知識寶藏使愛書人來到這猶如置身於書香天堂。室內閱讀區桌椅經過精心設計，與建築相呼應；室外則有木棧道桌椅和閱讀平台，邊閱讀邊感受著微風徐徐吹過，與大自然一起沉浸在書的世界。想歇息時走到戶外，看著一整片樹林綠意盎然，還有生態荷花池，不只能帶走眼睛疲憊，連身心都得到放鬆。

屋頂為輕質生態屋頂，設有太陽能光電板發電，可發電16千瓦電力，並採大量陽台深遮陽及垂直木格柵，減少熱輻射進入室內，降低耗能達到節能效果。綠化屋頂及斜坡草坡設計可涵養水分自然排水至雨水回收槽，再利用回收水澆灌植栽及沖水馬桶，達到綠化與減低水資源浪費。

建物使用木材及鋼材，建材皆可回收再利用，減少廢棄物對環境的破壞。在室內健康與環境指標方面，對於木材建材除做白蟻防治外，並使用生態塗料及免除不必要的裝修工程，降低污染及有毒物質的釋放，避免影響人體健康。

來到北投，除了可以泡溫泉，也可以來享受書香與綠意融合的森林浴！
&nbsp;


臺北市立圖書館北投分館(中文簡介影片)

&nbsp;
&nbsp;', is_active = TRUE
WHERE attraction_name = '北投圖書館';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '臺北市立圖書館北投分館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221368'
FROM attraction
WHERE attraction_name = '臺北市立圖書館北投分館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221369'
FROM attraction
WHERE attraction_name = '臺北市立圖書館北投分館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221370'
FROM attraction
WHERE attraction_name = '臺北市立圖書館北投分館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221371'
FROM attraction
WHERE attraction_name = '臺北市立圖書館北投分館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221372'
FROM attraction
WHERE attraction_name = '臺北市立圖書館北投分館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221366'
FROM attraction
WHERE attraction_name = '臺北市立圖書館北投分館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221367'
FROM attraction
WHERE attraction_name = '臺北市立圖書館北投分館';

UPDATE attraction
SET attraction_name = '南港山系_象山親山步道', description = '象山海拔183公尺，步道全長1450公尺，全程約需1小時40分。因外形似象頭而得名，位於臺北盆地東南方的信義區，與虎山地質相同主要由砂岩組成，因造山作用步道中可見黃褐色陡峭的岩壁與巨石，加上自然環境生物、鳥類種類繁多，使得整座山如同一座天然生態樂園般，成為民眾接近淺山、享受戶外綠林悠閒時光的好去處。

象山擁有稜線、岩壁、山坡、山窪、山谷等各種不同微環境，因而孕育出數十種蕨類。蕨類在象山處處可見，有的附著在樹幹上，有的長在岩石、坡地上，有的密佈在潮濕的林下。其中金狗毛蕨族群龐大，數量居臺北市之冠，在過去醫藥不發達的年代，它可是民間用來止血的最佳良藥。

另外在開闊、向陽且潮濕山窪區，還有自侏儸紀時期就存在的古老蕨類「筆筒樹」。筆筒樹群聚可是臺北市區最珍貴的生態特色，因為筆筒樹成群林立的現象，全世界只有臺灣北部才能看得到。

象山位在四獸山步道系統中最高點，由於前方無屏障，登高遠望視野遼闊，不僅信義商圈一覽無遺－101金融大樓、世貿中心、華納威秀、新光三越等醒目建築歷歷可數，臺北盆地風光也盡收眼底。其尾稜延伸嵌入信義區中強公園，成為當地居民晨昏散步的最佳去處，也是近山民眾假日休閒、舒緩身心的綠色地帶。

六巨石
象山上巨石林立的奇特景象，又稱老萊峽。從這裡攀上巨石可以一覽繁華的信義商圈，是一處熱門的拍照景點，清晨上山可以欣賞臺北101大樓在晨曦中初醒的景象，黃昏更可欣賞信義區都會華廈，夕陽餘暉西下、華燈初上的夜晚景象，十分亮麗耀眼。

逸賢亭（象山頂）
位於逸賢亭象山頂、六角亭旁步道盡頭的平台，視野展望極佳，可以欣賞象山的全貌，尤其是象頭與象鼻頗具傳神。鼻樑處即為永春高中，長長的象鼻子則是稜線深入松山路與松德院區之間的平台。

一線天
象山親山步道近松德院區方向有處名為一線天駐腳點，因兩壁山脊線十分接近，巨崖岩壁突出遮天，山友自步道仰頭望天，只見崖壁縫隙間的天空又窄又細，因而稱為一線天。

至於鳥瞰台北盆地的最佳位置，自然是位於稜線上、視野開闊的「超然亭」；有此「超然」名號，便是因為由此觀景居象山眾涼亭之冠。站立於超然亭的平台上，近可見山下的信義計畫區，放遠望去則是圓山、北投焚化爐、觀音山及大屯火山群各景點，不論是跨年或國慶日施放煙火，不少人還會特地來此觀賞花火綻放，足見其魅力所在。

繞行到巨石公園階梯附近，有一塊碩大的巨石，上面有人為雕刻出來的石階，可拾級而上眺望臺北盆地。一路前行間，由左側山腰、山脊再下到右側山腰線，從不同角度俯瞰臺北盆地之美，象山迷人之處盡在其中。

步道沿途都設有解說牌，引導親山訪客認識整個山頭的特色，所以這裡也是最受歡迎的自然教室。一路上不愁沒有生態導覽，只要「按圖索驥」，自己就是山林解說員。

潮濕的環境中，蝸牛的族群也十分可觀，像是斯文豪氏大蝸牛、煙管蝸牛，幾乎在整個山區都看得到。這本是低海拔的原始闊葉林，生態豐富多元，綠意萬千的山林，還有更多的驚喜等待你自己慢慢去發掘呢！

登上象山之後，如果你的體力充沛，或是想伸展筋骨，步道兩旁還有許多強體力及肺活量的體能設施，只見大夥在山頂的逸賢亭打個尖、做個操，還有精力無窮的小朋友穿梭其間，運動休閒一兼二顧，很適合全家來活動。', is_active = TRUE
WHERE attraction_name = '南港山系-象山親山步道';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222131'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222132'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222133'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222134'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222135'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222136'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222137'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222138'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/222129'
FROM attraction
WHERE attraction_name = '南港山系_象山親山步道';

UPDATE attraction
SET attraction_name = '國立國父紀念館', description = '※國父紀念館「大會堂暨周邊設施工程」工期預計自113年至115年底，目前整修中未開放。

於1972年落成的國父紀念館，為紀念國父孫中山先生之革命行誼、人格，並發揚其思想學說，由建築師王大閎設計。除供海內外人士瞻仰國父之外，也兼具文化藝術教育、生活休閒及學術研究之功能。

巍峨莊嚴的建築本體，座落在綠草如茵，花木扶疏的中山公園，成為臺北東區一顆璀璨的明星。這裡也為國內的文化藝術帶來嶄新的面貌，許多的藝術活動都在這裡進行，像是文藝走廊、文化藝術展覽活動、青年創作等。另外也有絕佳的室內表演空間，可以辦理劇場展演活動，像是大家熟悉所的金馬獎、金鐘獎等，都在此舉行過。

晨間時刻，只見老爺爺、老奶奶們在這兒打太極拳、跳土風舞。在假日時刻，寬闊的廣場，更是親子玩飛盤、玩直排輪、散步休閒的好去處。', is_active = TRUE
WHERE attraction_name = '國父紀念館';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '國立國父紀念館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63542'
FROM attraction
WHERE attraction_name = '國立國父紀念館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63543'
FROM attraction
WHERE attraction_name = '國立國父紀念館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63544'
FROM attraction
WHERE attraction_name = '國立國父紀念館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63546'
FROM attraction
WHERE attraction_name = '國立國父紀念館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63548'
FROM attraction
WHERE attraction_name = '國立國父紀念館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63550'
FROM attraction
WHERE attraction_name = '國立國父紀念館';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63551'
FROM attraction
WHERE attraction_name = '國立國父紀念館';

UPDATE attraction
SET attraction_name = '地熱谷_地獄谷_鬼湖', description = '地熱谷位在北投溫泉公園旁邊，是北投溫泉的源頭之一，因為終年瀰漫著硫磺煙霧，讓人聯想到恐怖的地獄，所以又被稱為「地獄谷」或「鬼湖」。這裡的溫泉是大屯山火山群內水溫最高的溫泉，硫磺煙霧濔漫的景色，如夢似幻，有如仙境一般，是日治時代臺灣八景十二勝之一。

地熱谷中的石頭具有放射性元素「鐳」，叫做「北投石」，是世界數千種礦石中，唯一用臺灣地名命名的礦石，目前只有臺灣北投和日本玉川有這種礦物。最近幾年為了復育北投石，成立北投石保護區，來此參觀，除了能感受到溫泉鄉的情懷，更能對這獨特的礦石有更深入的瞭解。

地熱谷的泉水溫度約在80℃至100℃之間，屬於鹽酸酸性泉，溫泉水質酸鹼度很高，具有腐蝕性，俗稱「青磺泉」和「磺水頭」。之前常有遊客在地熱谷利用高溫的泉水煮「溫泉蛋」，不過近年來為了保護溫泉的水質，並且避免遊客在此跌倒發生意外，已經禁止民眾在地熱谷煮蛋了！來地熱谷玩，可別再帶著食物前往，以免掃興囉！

現在的地熱谷經過改造後以嶄新風貌重現，建置環湖步道以及設置溫泉體驗設施，包含入口意象手湯(淨手礦泉湯)、大斜面設計的愛情座椅。遊客可以沿著新建置的環湖步道漫步一圈，體驗大自然的蒸氣Spa，搭配園區植栽美化，展現仙境般全新風貌。', is_active = TRUE
WHERE attraction_name = '地熱谷';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282092'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282084'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282085'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282086'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282087'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282088'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282089'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282090'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/282091'
FROM attraction
WHERE attraction_name = '地熱谷_地獄谷_鬼湖';

UPDATE attraction
SET attraction_name = '基隆河河濱自行車道', description = '從左岸的林安泰疏散門進入河濱自行車道，遊客可以看見記錄著基隆河緣起、整治故事的解說牌，讓民眾在運動休閒之餘，還能了解基隆河長長的歷史故事。

大佳河濱公園是屬河床填土後的新生地，放眼望去盡是綠野草皮，靠西之地建設成都會型綠化公園，其中以中山橋到大直橋間段的親水公園最具特色，地標「希望之泉」的噴泉設計，高達25層樓高的扇形噴泉水幕，精采的水舞、夜晚亮麗的五彩霓虹燈光，整個河濱之地瞬間成為繽紛亮麗，背景在圓山飯店古典輝煌的紅色建築陪襯下，景致格外好看、令人難忘，可以說是市區閤家老少、戀愛男女朋友約會的最佳去處。

遊客若是從右岸的美堤疏散門進入，也同樣可以看見堤防壁上用圖案細說基隆河的歷史故事，同樣精彩耀眼，夜遊基隆河，更可看到眩麗的摩天輪及內湖科技園區夜景。', is_active = TRUE
WHERE attraction_name = '基隆河左、右岸親水';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '基隆河河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/65476'
FROM attraction
WHERE attraction_name = '基隆河河濱自行車道';

UPDATE attraction
SET attraction_name = '士林官邸_士林官邸公園', description = '士林官邸公園約佔地12.9公頃，因所在地緊鄰中山北路，可快速直達總統府，並被福山山系所環抱，優越的地勢、絕佳的地理位置，故自民國三十九年起成為先總統蔣公日常起居之官邸使用。也因官邸設立於此的緣故，鄰近區域嚴禁改建及新建，使得官邸公園能維持原有的自然景觀，蟲鳴鳥叫、景色秀麗，是近郊休閒遊憩的絕佳場所。
1996年，官邸首度開放市民觀賞園藝與休憩使用。玫瑰園，是蔣夫人最喜愛的花園；西式庭園中浪漫美好的風光，是新人婚紗照最常取景的地方；中式庭園裡的拱橋、曲池、流水等東方庭園造景，則令人彷彿置身古代中式庭院。
官邸公園主要分為露天音樂臺、玫瑰園、主題園區、內花園、正館、踏青區、西式庭園、中式庭園、凱歌堂、新蘭亭、園藝展覽館和慈雲亭。每年3月可在蔣夫人最喜愛的玫瑰園內，欣賞近100種、約2,000株的玫瑰盛開；主題園區、踏青區則是每年菊展、鬱金香展精心規劃的重點展區；在西式與中式庭園則可欣賞到美麗的當季草花花壇；新蘭亭、園藝展覽館依照不同時節亦有不定期的園藝花卉植栽展出，全年各式花卉輪番上陣，接力歡迎各位的到訪。
凱歌堂為蔣家人禮拜及受洗之處。新蘭亭建於民國三十九年，又名壽亭，為中式四角狀建築，是每年蔣公作壽的地方，也是舉辦各類花卉展覽之地。慈雲亭建於福山之上，為兩層樓方形亭，是老總統為懷念母親所建。
士林官邸每年年初及年末都會舉辦各式花展，像是鬱金香展、玫瑰花展、蝴蝶蘭展、菊展&hellip;等，而最為廣為人知的就是菊展和鬱金香展，利用花卉搭配上園區造景，打造出色彩繽紛的展場。

菊展
接近秋冬的11至12月就是全台知名花展之一的菊展。藉由大立菊、造型菊、小菊及菊科草花搭配每年不同主題的展場造型物與園藝造景，將士林官邸打造成大型花園，吸引各地遊客前來觀賞。

鬱金香展
每年春節過後的2月為士林官邸鬱金香展，展出超過10萬株來自荷蘭及日本鬱金香花海，並設置異國裝置藝術，讓人彷彿置身於國外。

士林官邸公園於民國八十五年正式開放民眾參觀，為提供更多更好的服務，也積極加強各項的整理規劃及建設，成為臺北市區中另一處供民眾休憩的景點。', is_active = TRUE
WHERE attraction_name = '士林官邸';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221280'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221281'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221283'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221284'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221285'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221287'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/478213'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/478214'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/478215'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221278'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/221279'
FROM attraction
WHERE attraction_name = '士林官邸_士林官邸公園';

UPDATE attraction
SET attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集', description = '大稻埕原是平埔族的居住地，因萬華（艋舺）同安人發生激烈的械鬥，造成族人移至大稻埕定居，開始大稻埕淡水河旁商店和房屋的興建，淡水港開放後，大稻埕在劉銘傳的治理下成為臺北城最繁華的物資集散中心，當中以茶葉、布料為主要貿易交易，當時的延平北路及貴德街一帶便是商業活動的重心，也讓大稻埕早年的歷史多采多姿、令人回味。', is_active = TRUE
WHERE attraction_name = '大稻埕碼頭';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182690'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182691'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182692'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182693'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182698'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182702'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/182703'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/214149'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/223127'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/223128'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/223129'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63302'
FROM attraction
WHERE attraction_name = '大稻埕碼頭_大稻埕碼頭貨櫃市集';

UPDATE attraction
SET attraction_name = '新北投溫泉商圈', description = '北投溫泉從日據時代便有盛名，喜愛泡湯的日本人自然不會錯過，瀧乃湯、星乃湯、鐵乃湯就是日本人依照溫泉的特性與療效給予的名稱，據說對皮膚病、神經過敏、氣喘、風濕等具有很好的療效，也因此成為了北部最著名的泡湯景點之一。

新北投溫泉的泉源為大磺嘴溫泉，泉質屬硫酸鹽泉，PH值約為3~4之間，水質呈黃白色半透明，泉水溫度約為50-90℃，帶有些許的硫磺味 。

目前北投的溫泉旅館、飯店、會館大部分集中於中山路、光明路沿線以及北投公園、地熱谷附近，每一家都各有其特色，多樣的溫泉水療以及遊憩設施，提供遊客泡湯養生。

鄰近的景點也是非常值得造訪，例如北投溫泉三寶的吟松閣、星乃湯、瀧乃湯以及記錄臺灣第一家溫泉旅館的天狗庵史蹟公園，都有著深遠的歷史背景。

而北投公園、北投溫泉博物館、北投文物館、地熱谷等，更是遊客必遊的景點，來到北投除了可以讓溫泉洗滌身心疲憊，也可以順便深入了解北投溫泉豐富的人文歷史。', is_active = TRUE
WHERE attraction_name = '新北投溫泉區';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292631'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292623'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292624'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292625'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292626'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292627'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292628'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292629'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292630'
FROM attraction
WHERE attraction_name = '新北投溫泉商圈';

UPDATE attraction
SET attraction_name = '新店溪河濱自行車道', description = '這段由大稻埕碼頭沿著延平河濱公園所興建的自行車道，在遊騎之餘還可以走訪相鄰的文化古蹟，在動靜相宜的休閒活動中，既可強身還可陶醉於文化洗禮。周邊著名的文化觀光景點，如迪化街、霞海城隍廟、林柳新紀念偶戲博物館、酒泉街方向的臺北孔廟、保安宮等景點，從中體驗文化饗宴。

沿途景觀包括大稻埕碼頭咖啡廣場、唐山帆船造景、碼頭拱橋、淡水河遠眺等，還結合藍色公路航線，帶著腳踏車一起前進到關渡碼頭，甚至淡水漁人碼頭、八里左岸等，享受多樣之河濱遊憩樂趣。這段自行車道在華江橋之後便進入新店溪沿岸，橫跨新店溪的多座橋更可帶領您進入大漢溪沿岸的自行車道，因為周圍的建築物林立，更凸顯這片河畔公園的可貴，新店溪、大漢溪的沿岸景色，充滿「城市中的綠地」的感覺，這一長串的河濱公園，穿越了鶯歌、土城、板橋、中永和、新店，每年的10月到隔年3月，更可以欣賞遠道而來的雁鴨嬌客及保育候鳥，結合育樂、健身、美食等樂趣，讓整天的自行車騎乘活動充實而豐富。', is_active = TRUE
WHERE attraction_name = '新店溪、大漢溪與淡水河自行車道';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64305'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64308'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64313'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180737'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64294'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64297'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64300'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64302'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64304'
FROM attraction
WHERE attraction_name = '新店溪河濱自行車道';

UPDATE attraction
SET attraction_name = '景美溪河濱自行車道', description = '有青山綠水相伴的景美溪河濱自行車道，沿線有動物園，政大球場及青草綠茵，溪流常有魚群穿梭，適合攜家帶眷全家出遊的路線。

沿線的景觀相當豐富，翠綠草地，清澈溪流讓人感覺非常舒適，此外，於道南河濱公園內還設有各式各樣的運動場所，如籃球場、溜冰場、羽球場等，每到傍晚便可看到許多人或走或騎自行車到這兒來進行各種運動，是一個充滿活力的自行車道。', is_active = TRUE
WHERE attraction_name = '景美溪左、右岸自行車道';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '景美溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63334'
FROM attraction
WHERE attraction_name = '景美溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63329'
FROM attraction
WHERE attraction_name = '景美溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63331'
FROM attraction
WHERE attraction_name = '景美溪河濱自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63333'
FROM attraction
WHERE attraction_name = '景美溪河濱自行車道';

UPDATE attraction
SET attraction_name = '梅庭(目前暫停開放)', description = '※梅庭目前進行修復再利用工程，於113/5/28起閉館整修，預計115年開館

「北投梅庭」約建於1930年代末期，是一棟見證戰爭時代與順應北投風土而建的和洋式別莊。屹立在北投公園近百年，自日本時代起，所有者包括日本總督府、陸軍大臣、台北州，1945年二次世界大戰後，主要作為私人住宅使用，2006年因其建築特色登錄為臺北市歷史建築。

順地勢臨靠北投溪而建，將建物南側之山景與北投溪流結合為一，上層為日式木構架，下層為RC構造(鋼筋混凝土建築Reinforced Concrete)之地下室，作為防空避難室用，在當時代的日式街屋裡，顯得獨特與具有歷史價值。外門柱有書法家于右任題字之「梅庭」門牌，庭院內有受「臺北市樹木保護自治條例」保護之臺北市保護樟樹(編號1679)，週邊圍牆以停採之「唭哩岸石」為建材，屋內空間配置講究，利用北投豐富的地熱資源，曾設置「溫泉浴室」， 建有「閣樓」瞭望、儲藏物品，並有調節室內溫度、排濕防潮功能，同時也作為下層樓面的天花板以及支撐建築主要結構所在；玄關處貼有「釉面馬賽克」磁磚加上洗石子的門柱，彰顯工藝之美，牆面上的「八角窗」設計，為日本時代興起之擬洋風裝飾，內斂雅致，更是顯出富有有時代感與建造之美。

2021年由臺北市文化局委任台北市文化基金會營運維護，為提升文化資產再利用與在地推廣，未來將延續北投特有的人文特色，透過藝術展覽、教育活動，創造歷史人文與藝術文化相結合的樂活空間。', is_active = TRUE
WHERE attraction_name = '梅庭';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '梅庭(目前暫停開放)';

UPDATE attraction
SET attraction_name = '臺北自來水園區', description = '座落於公館商圈旁的臺北自來水園區，是一處完美融合歷史古蹟、工業遺產、親子遊樂與環境教育的多元化休閒空間。園區的核心，無疑是那座被列為國家三級古蹟的自來水博物館。這棟建於1908年（日治時期）的臺北水道地唧筒室（即抽水站），是臺灣近代自來水系統的起點，其建築本身就是一件藝術品，成為臺北熱門的婚紗攝影與外拍聖地之一。走進博物館內部，挑高的空間依然保存著當年運作的大型柴油馬達、抽水幫浦與配電盤等機組設備，讓遊客能親身感受百年前工業時代的震撼脈動。

一到炎炎夏日，這裡便會化身為親子樂園。廣闊的園區內設有水鄉庭園與親水體驗區，提供大型戲水池、滑水道、噴泉與水砲等豐富設施，是孩子們消暑的最佳去處；而非夏季期間，這裡也是一片適合散步休憩的開闊廣場。此外，園區內還隱藏著一條觀音山生態步道，步道綠意盎然，登頂後可探訪同樣具有歷史的觀音山蓄水池。除了休閒功能，園區也肩負著水資源的教育使命，透過互動裝置與展覽，向大眾傳遞水資源保育的重要性。從百年古蹟的建築之美、夏日限定的沁涼歡笑，到生態步道的自然綠意，臺北自來水園區已成為一個適合全家大小，兼具知性與感性的城市綠洲。', is_active = TRUE
WHERE attraction_name = '自來水博物館';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63614'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180704'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180707'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180708'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180709'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180711'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180713'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180714'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180716'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180717'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/180718'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63612'
FROM attraction
WHERE attraction_name = '臺北自來水園區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63613'
FROM attraction
WHERE attraction_name = '臺北自來水園區';

UPDATE attraction
SET attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區', description = '穿梭在臺北市萬華區的老舊巷弄中，有一處名為「剝皮寮」的老街區，這裡依然延續著百餘年前清代街道的風貌，紅色的磚牆、拱型的騎樓、雕花的窗櫺，呈現典雅樸實之美。

剝皮寮歷史街區位於龍山寺旁，康定路、廣州街及昆明街口，街區內保存有相當完整的清代街型、清代傳統店屋，其建築空間見證了艋舺市街的發展，擁有獨特之歷史文化和建築特色。

「臺北市鄉土教育中心」以融入式教育與文化之理念，使其作為推展鄉土教育之園地，將學校教育和社區文化相結合，規劃不同主題展覽，及剝皮寮相關歷史特展，並辦理各項教育活動，以達寓教於樂的功能。

近年來，剝皮寮街區的發展除了推廣電影文化與活動及教育，更廣納優質的藝文展演，成為文化體驗平臺的入口，期望串聯在地特色，創造故事的流動與回憶，賦予這個空間更多的意義。詳情可見剝皮寮歷史街區營運中心(網址 http://www.bopiliao.taipei)', is_active = TRUE
WHERE attraction_name = '臺北市鄉土教育中心(剝皮寮歷史街區)';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176584'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176585'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176586'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176587'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176588'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176589'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176576'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176577'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176578'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176579'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176580'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176581'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176582'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/176583'
FROM attraction
WHERE attraction_name = '臺北市鄉土教育中心_剝皮寮歷史街區';

UPDATE attraction
SET attraction_name = '國民革命忠烈祠', description = '背倚青山、面臨基隆河的「國民革命忠烈祠」，是中華民國崇祀殉國將士的最高殿堂。其建築群極為宏偉壯麗，仿照北京故宮太和殿結構而建，整體格局氣勢磅礴，一踏入便能感受到莊嚴肅穆的氛圍。

忠烈祠最吸引國內外遊客目光的，莫過於每個整點上演的「三軍儀隊交接儀式」。由陸、海、空三軍儀隊輪流擔任的衛兵，身穿筆挺的軍服，手持擦得雪亮的鋼槍，以一絲不苟、分毫不差的精準步伐，在廣闊的廣場上進行交接展演。從大門走到大殿的儀式中，他們穩健的步伐、響亮的鞋釘聲，以及高難度的耍槍動作，完美展現了軍人的儀態與紀律。在衛兵哨位上，他們必須如雕像般紋風不動，不論風吹日曬，堅毅地守護著這座英靈聖殿，這場結合力與美的儀式，已成為忠烈祠最生動的象徵。', is_active = TRUE
WHERE attraction_name = '臺北忠烈祠';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215692'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215693'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215694'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215695'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215687'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215688'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215689'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215690'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/215691'
FROM attraction
WHERE attraction_name = '國民革命忠烈祠';

UPDATE attraction
SET attraction_name = '行天宮北投分宮_忠義廟', description = '行天宮北投分宮，俗稱「忠義廟」，主祀關聖帝君，位於臺北市北投區中央北路4段18巷50號，係臺北市民權東路上香火鼎盛行天宮的分宮，但建廟歷史卻比臺北本宮更早，原臺鐵「忠義站」及現在捷運「忠義站」之站名，即因位置鄰近「忠義廟」而得名。

「關帝廟行天宮」，此為昔日信眾所熟知的「九台街恩主公廟」，原位於今日臺北市中山區新興國中附近。「關帝廟行天宮」香火鼎盛，後來因廟地被劃歸為學校用地，廟方不得不積極另覓廟址準備搬遷，結果於民國45年在北投嗄嘮別(今忠義山)尋獲建廟吉地。由行天宮三宮建設人-玄空師父挹注資金建設，並於民國54年5月31日慶成，展現出三殿式的大廟格局。

北投行天宮廟區範圍約8公頃，廟殿建築雄偉，除附設圖書館外，區內花木扶疏、自然生態豐富，步道、庭園造景、休憩涼亭、停車場及公廁等設施規劃完善，且為市政府規劃之忠義山親山步道之起點。

從山下順著階梯而上，首先映入眼簾的是一大片綠油油的青草地，庭園造景及椰林大道；再拾階往上，穿過日、月門，方才來到北投分宮開闊的前殿。

廟埕十分寬敞，紅牆與灰色的石板地，在藍天下交織出一片祥和的氛圍。穿過山門，放眼看到典雅的玉皇殿及鐘鼓樓，展現的是莊麗的建築之美。

在參拜玉皇殿、後殿及三元殿之後，轉往後山方向，更可感受到寧靜的自然之美。漫步在林木蒼鬱的幽徑，或仰望綿密的修竹，或凝視歷盡滄桑的奇岩，益發覺得景緻清幽。再從右側的八百階登高，更可遠眺關渡平原和淡水河，視野相當遼闊又舒暢，是北淡線旅遊踏青、沉澱心靈的最佳景點。', is_active = TRUE
WHERE attraction_name = '行天宮北投分宮-忠義廟';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292476'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292477'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292478'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292479'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292480'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292481'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292483'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292484'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/292485'
FROM attraction
WHERE attraction_name = '行天宮北投分宮_忠義廟';

UPDATE attraction
SET attraction_name = '關渡_金色水岸_八里左岸自行車道', description = '基隆河溫柔地擁抱著社子島，在匯入淡水河前，劃開一道優美的弧線。在其北岸，磺港溪以西的這片土地，是繁華臺北裡一方珍貴的田園綠洲。這裡的稻浪隨風搖曳，一路綿延至河口的紅樹林保護區，彷彿一條綠色廊道，將都市的喧囂隔絕於外。

騎著單車穿梭其間，最能領略早期農村那份樸實與自在。當夕陽餘暉灑落，漫步於堤岸，晚風輕拂，鳥鳴啁啾，遠方關渡自然公園的蓬勃生機盡收眼底，交織成一幅充滿野趣與浪漫的閒適畫卷。

此處的自行車道為開放式路徑，西起關渡宮，沿著防潮堤向東，至八仙福德祠後轉往北方，穿越遼闊的關渡平原，直至北投中央北路。步道的終點，便是政戰學校西側的稻香路。若是無法自行攜帶單車的遊人，不妨以關渡宮為起點。這裡靠近捷運站，租借單車或協力車都相當方便。隨著時間推移，宮前的河堤轉變為平坦的人行步道，原先停泊於中港河的漁船也移至淡水河邊，呈現出另一種開闊、清新的水岸風情。', is_active = TRUE
WHERE attraction_name = '關渡、金色水岸、八里左岸自行車道';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '關渡_金色水岸_八里左岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63340'
FROM attraction
WHERE attraction_name = '關渡_金色水岸_八里左岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63335'
FROM attraction
WHERE attraction_name = '關渡_金色水岸_八里左岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63337'
FROM attraction
WHERE attraction_name = '關渡_金色水岸_八里左岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63339'
FROM attraction
WHERE attraction_name = '關渡_金色水岸_八里左岸自行車道';

UPDATE attraction
SET attraction_name = '財團法人台北市關渡宮', description = '<!--
關渡宮是臺灣北部最古老的媽袓廟，其歷史背景可以追朔到清順治年間，由開山石興和尚自福建奉請聖母來臺，當時名稱為「天妃廟」，其後乾隆、道光、光緒年間多次整修，於第5次重修並遷建現址，自石興和尚來臺已有340年以上的歷史。
關渡宮殿內、殿外的石牆、石柱、石獅，都雕滿了歷史故事，作品細膩壯觀。關渡宮的祭典是每年農曆3月23，元宵節和中元節普渡也是年度大事，來自各地參拜的人潮絡繹不絕。由於香火鼎盛，關渡宮不斷擴建，除聖母殿、觀音殿、文昌殿外並有古佛洞，廣渡寺、鼓樓、鐘樓等，面積廣大。

另外每年元宵節，關渡宮一定會有電動花燈展出，從山下廟宇到山上後花園，大大小小的燈籠及各方精製的花燈，充滿了年節氣息，難怪每年到了這時候，滿滿都是人潮，大人帶著小孩來這裡賞燈並求平安，希望未來一年都可以順順利利。



-->台北市關渡宮擁有三百多年歷史，主祀天上聖母媽祖，是北台灣地區最早的媽祖廟，而除了參拜天上聖母媽祖與諸神明外，來到這裡還可以觀賞許多珍貴的古蹟文物以及豐富的宮廟建築藝術。由於位居大屯、觀音二山的餘脈相交，臨淡水河與基隆河的滙流，風光景緻一覽無遺，每當落日餘暉，宏偉壯闊的景觀，更是令人驚嘆。




&nbsp;
&nbsp;



附近行程推薦:推薦行程', is_active = TRUE
WHERE attraction_name = '關渡宮';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '財團法人台北市關渡宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64043'
FROM attraction
WHERE attraction_name = '財團法人台北市關渡宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64045'
FROM attraction
WHERE attraction_name = '財團法人台北市關渡宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64046'
FROM attraction
WHERE attraction_name = '財團法人台北市關渡宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64049'
FROM attraction
WHERE attraction_name = '財團法人台北市關渡宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64054'
FROM attraction
WHERE attraction_name = '財團法人台北市關渡宮';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/64062'
FROM attraction
WHERE attraction_name = '財團法人台北市關渡宮';

UPDATE attraction
SET attraction_name = '關渡碼頭', description = '關渡原名甘豆門，因背倚觀音山和大屯山，面向淡水河，成為一處地勢險要的港口，早年先民由關渡碼頭進入移居臺灣北部開墾，因此關渡的開發甚早，後因兩河(基隆河、淡水河)河口泥沙淤積，水運才逐漸沒落。

關渡碼頭位於關渡自然公園及關渡宮旁，每當假日或夜晚均可見遊客駐足關渡碼頭週邊散步休息，亦有許多單車族由八里經關渡大橋前來，或由淡水前來，沿途風光明媚，是一處極佳的賞景地點。', is_active = TRUE
WHERE attraction_name = '關渡碼頭-甘豆門';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '關渡碼頭';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63313'
FROM attraction
WHERE attraction_name = '關渡碼頭';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63315'
FROM attraction
WHERE attraction_name = '關渡碼頭';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63318'
FROM attraction
WHERE attraction_name = '關渡碼頭';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63319'
FROM attraction
WHERE attraction_name = '關渡碼頭';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63320'
FROM attraction
WHERE attraction_name = '關渡碼頭';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63322'
FROM attraction
WHERE attraction_name = '關渡碼頭';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63323'
FROM attraction
WHERE attraction_name = '關渡碼頭';

UPDATE attraction
SET attraction_name = '雙溪生活水岸自行車道', description = '從陽明山國家公園發源的雙溪，流經東吳大學之後，轉往公路北側，河濱綠地公園也由此綿延展開，河濱自行車道順勢闢建於左右兩岸，成為臺北市河川單車路網中，最貼近住宅區也維護得極為完善的短小精緻路徑。

景色優美的雙溪河畔，引領平日生活繁忙的都市人，找到一條解放疲憊身心的綠色隧道，由雙溪左岸在銜接百齡橋右岸自行車道，百齡橋右岸河濱公園是玩橄欖球愛好者聚集之處，也常見足球隊伍相互較勁，單車族群也可加入這片青青草原，一路踏騎到承德橋下，順路造訪臺北市最後舢舨碼頭「三腳渡」。', is_active = TRUE
WHERE attraction_name = '雙溪生活水岸';
DELETE iu FROM image_url iu
JOIN attraction a ON iu.attraction_id = a.id
WHERE a.attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63344'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63345'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63349'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63350'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63352'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63354'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63357'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63359'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';
INSERT INTO image_url (attraction_id, url)
SELECT id, 'https://www.travel.taipei/image/63362'
FROM attraction
WHERE attraction_name = '雙溪生活水岸自行車道';

-- replaced_by_other_attraction

UPDATE attraction
SET is_active = FALSE
WHERE attraction_name = '台北探索館';

-- removed

UPDATE attraction
SET is_active = FALSE
WHERE attraction_name = '臺北啤酒工廠(原建國啤酒廠)';

UPDATE attraction
SET is_active = FALSE
WHERE attraction_name = '琉園水晶博物館(暫時休館)';

-- split

UPDATE attraction
SET is_active = FALSE
WHERE attraction_name = '陽明山溫泉區';
