import json
from pathlib import Path
import sys

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))

from app.db import my_pool

# See docs/attraction-mapping-rules.md for mapping definitions.

API_DATA_PATH = BASE_DIR / "data" / "taipei-api-attractions.json"
MAPPING_PATH = BASE_DIR / "data" / "attraction-manual-mapping.json"
OUTPUT_SQL_PATH = BASE_DIR / "database" / "insert_attractions.sql"


def load_json(path):
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def escape_sql(value):
    if value is None:
        return "NULL"

    return str(value).replace("'", "''")

def build_api_by_name(api_attractions):
    api_by_name = {}

    for item in api_attractions:
        api_by_name[item["name"].strip()] = item

    return api_by_name

def get_db_attractions_by_name(cursor):
    # Get existing attraction data: transport, category_id
    cursor.execute("""
        SELECT id, attraction_name, transport
        FROM attraction
    """)
    rows = cursor.fetchall()

    result={}
    for row in rows:
        result[row["attraction_name"]] = row

    return result

def get_db_categories_by_name(cursor):
    # Convert category names into category IDs.

    cursor.execute(
        """
        SELECT id, category_name
        FROM category
        """
    )

    rows = cursor.fetchall()
    result = {}

    for row in rows:
        result[row["category_name"]] = row["id"]

    return result

def get_db_mrt_ids_by_attraction_id(cursor):
    # target: get mrt_id
    cursor.execute("""
        SELECT attraction_id, mrt_id
        FROM attraction_mrt
    """)
    rows = cursor.fetchall()

    result = {}
    for row in rows:
        attraction_id = row["attraction_id"]

        if attraction_id not in result:
            result[attraction_id] = []
        
        if row["mrt_id"] is not None:
            result[attraction_id].append(row["mrt_id"])

    return result

def get_db_mrt_ids_by_name(cursor):
    # Convert MRT names into MRT IDs.

    cursor.execute(
        """
        SELECT id, mrt_name
        FROM mrt
        """
    )

    rows = cursor.fetchall()
    result = {}

    for row in rows:
        result[row["mrt_name"]] = row["id"]

    return result


def generate_insert_attraction_sql(new_attr, category_id, transport):
    # Generate INSERT statement for attraction table.

    sql_lines = [
        "-- insert attraction",
        "INSERT INTO attraction (",
        "    attraction_name,",
        "    description,",
        "    category_id,",
        "    address,",
        "    transport,",
        "    latitude,",
        "    longitude,",
        "    is_active",
        ") VALUES (",
        f"    '{escape_sql(new_attr['name'])}',",
        f"    '{escape_sql(new_attr['introduction'])}',",
        f"    {category_id},",
        f"    '{escape_sql(new_attr['address'])}',",
        f"    '{escape_sql(transport)}',",
        f"    {new_attr['nlat']},",
        f"    {new_attr['elong']},",
        "    TRUE",
        ");",
        "",
        "SET @new_attraction_id = LAST_INSERT_ID();",
        "",
    ]

    return sql_lines


def generate_insert_image_sql(new_attr):
    # Generate INSERT statements for image_url table.

    sql_lines = []
    images = new_attr.get("images", [])

    for image_url in images:
        sql_lines.append(
            f"INSERT INTO image_url (attraction_id, url)\n"
            f"VALUES (@new_attraction_id, '{escape_sql(image_url['src'])}');"
        )
    sql_lines.append("")

    return sql_lines


def generate_insert_mrt_sql(mrt_ids):
    # Generate INSERT statements for attraction_mrt table.

    sql_lines = []

    for mrt_id in mrt_ids:
        sql_lines.append(
            "INSERT INTO attraction_mrt (attraction_id, mrt_id)\n"
            f"VALUES (@new_attraction_id, {mrt_id});"
        )
    sql_lines.append("")

    return sql_lines


def get_category_id(category_name, category_ids_by_name):
    category_id = category_ids_by_name.get(category_name)

    if category_id is None:
        raise ValueError(f"Category not found in database: {category_name}")

    return category_id

def get_mrt_ids(mrt_names, mrt_ids_by_name):
    mrt_ids = []

    for mrt_name in mrt_names:
        mrt_id = mrt_ids_by_name.get(mrt_name)

        if mrt_id is None:
            raise ValueError(f"MRT not found in database: {mrt_name}")

        mrt_ids.append(mrt_id)

    return mrt_ids


def main():
    api_attractions = load_json(API_DATA_PATH)
    mapping = load_json(MAPPING_PATH)

    sql_lines = [
        "-- Generated by scripts/generate_attraction_insert_sql.py",
        "-- Review before running on dev or EC2 database.",
        "",
    ]

    try:
        my_conn = my_pool.get_connection()
        my_cursor = my_conn.cursor(dictionary=True)

        api_by_name = build_api_by_name(api_attractions)
        db_attractions_by_name = get_db_attractions_by_name(my_cursor)
        category_ids_by_name = get_db_categories_by_name(my_cursor)
        mrt_ids_by_attraction_id = get_db_mrt_ids_by_attraction_id(my_cursor)
        mrt_ids_by_name = get_db_mrt_ids_by_name(my_cursor)

        # Replace:
        # Insert a different attraction that replaces an existing attraction.
        # The original attraction is deactivated by the update SQL generator.
        # Transport and MRT relations are reused from the original attraction.      
        sql_lines.extend(["-- replace", ""])

        replace_mapping = mapping.get("replaced_by_other_attraction", {})
        
        for old_name, replace_data in replace_mapping.items():
            new_name = replace_data["new_attraction"]

            old_attr = db_attractions_by_name.get(old_name)
            new_attr = api_by_name.get(new_name)

            if old_attr is None:
                print(f"Warning: DB attraction not found: {old_name}")
                continue

            if new_attr is None:
                print(f"Warning: API attraction not found: {new_name}")
                continue

            category_id = get_category_id(
                replace_data["category"],
                category_ids_by_name,
            )

            mrt_ids = mrt_ids_by_attraction_id.get(old_attr["id"], [])
            if not mrt_ids:
                print(
                    f"Warning: '{old_name}' has no MRT mapping to carry over."
                )

            sql_lines.extend(
                generate_insert_attraction_sql(
                    new_attr=new_attr,
                    category_id=category_id,
                    transport=old_attr["transport"],
                )
            )
            sql_lines.extend(generate_insert_image_sql(new_attr))
            sql_lines.extend(generate_insert_mrt_sql(mrt_ids))
            sql_lines.append("")

        # Add:
        # Insert a new attraction without a corresponding existing record.
        # Category, transport and MRT data are maintained manually.
        sql_lines.extend(["-- add", ""])

        add_mapping = mapping.get("add", [])

        for add_data in add_mapping:
            new_name = add_data["name"]
            new_attr = api_by_name.get(new_name)

            if new_attr is None:
                print(f"Warning: API attraction not found: {new_name}")
                continue

            category_id = get_category_id(
                add_data["category"],
                category_ids_by_name,
            )

            mrt_ids = get_mrt_ids(add_data["mrt"], mrt_ids_by_name)

            if not mrt_ids:
                print(f"Warning: '{new_name}' has no MRT mapping.")

            sql_lines.extend(
                generate_insert_attraction_sql(
                    new_attr=new_attr,
                    category_id=category_id,
                    transport=add_data.get("transport"),
                )
            )
            sql_lines.extend(generate_insert_image_sql(new_attr))
            sql_lines.extend(generate_insert_mrt_sql(mrt_ids))
            sql_lines.append("")

    finally:
        if "my_conn" in locals():
            my_conn.close()

    with OUTPUT_SQL_PATH.open("w", encoding="utf-8") as file:
        file.write("\n".join(sql_lines))

    print(f"SQL generated: {OUTPUT_SQL_PATH}")


if __name__ == "__main__":
    main()