import json
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
API_DATA_PATH = BASE_DIR / "data" / "taipei-api-attractions.json"
COMPARE_REPORT_PATH = BASE_DIR / "data" / "attraction-compare-report.json"
MAPPING_PATH = BASE_DIR / "data" / "attraction-manual-mapping.json"
OUTPUT_SQL_PATH = BASE_DIR / "database" / "update_attractions.sql"


# Category is not synchronized.
# Existing category assignments are preserved.
UPDATE_RULES = {
    "matched": {
        "description": False,
        "images": True,
    },
    "rename_and_update": {
        "name": True,
        "description": True,
        "images": True,
    },
}


def load_json(path):
    with path.open("r", encoding="utf-8") as file:
        return json.load(file)


def escape_sql(value):
    if value is None:
        return "NULL"

    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def build_api_by_name(api_attractions):
    api_by_name = {}

    for item in api_attractions:
        api_by_name[item["name"].strip()] = item

    return api_by_name

def generate_attraction_update_sql(old_name, new_name, api_attraction, update_rule):
    sql_lines = []
    update_parts = []

    if update_rule.get("name"):
        update_parts.append(f"attraction_name = {escape_sql(new_name)}")

    if update_rule.get("description"):
        update_parts.append(
           f"description = {escape_sql(api_attraction.get('introduction').strip())}"
        )

    update_parts.append("is_active = TRUE")

    if update_parts:
        sql_lines.append(
            "UPDATE attraction\n"
            f"SET {', '.join(update_parts)}\n"
            f"WHERE attraction_name = {escape_sql(old_name)};"
        )

    return sql_lines

# def generate_rename_update_sql(old_name, new_name, api_attraction):
#     sql_lines = []

#     update_parts = []

#     if UPDATE_RULES["rename_and_update"]["name"]:
#         update_parts.append(f"attraction_name = {escape_sql(new_name)}")

#     if UPDATE_RULES["rename_and_update"]["description"]:
#         update_parts.append(
#             f"description = {escape_sql(api_attraction.get('introduction'))}"
#         )

#     sql_lines.append(
#         "UPDATE attraction\n"
#         f"SET {', '.join(update_parts)}\n"
#         f"WHERE attraction_name = {escape_sql(old_name)};"
#     )

#     if UPDATE_RULES["rename_and_update"]["images"]:
#         images = api_attraction.get("images", [])

#         sql_lines.append(
#             "DELETE iu FROM image_url iu\n"
#             "JOIN attraction a ON iu.attraction_id = a.id\n"
#             f"WHERE a.attraction_name = {escape_sql(new_name)};"
#         )

#         for image in images:
#             image_url = image["src"]

#             sql_lines.append(
#                 "INSERT INTO image_url (attraction_id, url)\n"
#                 f"SELECT id, {escape_sql(image_url)} "
#                 "FROM attraction\n"
#                 f"WHERE attraction_name = {escape_sql(new_name)};"
#             )

#     return sql_lines

def generate_image_update_sql(attraction_name, api_attraction):
    sql_lines = []
    images = api_attraction.get("images", [])

    sql_lines.append(
        "DELETE iu FROM image_url iu\n"
        "JOIN attraction a ON iu.attraction_id = a.id\n"
        f"WHERE a.attraction_name = {escape_sql(attraction_name)};"
    )

    for image in images:
        image_url = image["src"]

        sql_lines.append(
            "INSERT INTO image_url (attraction_id, url)\n"
            f"SELECT id, {escape_sql(image_url)}\n"
            "FROM attraction\n"
            f"WHERE attraction_name = {escape_sql(attraction_name)};"
        )

    return sql_lines

def generate_deactivate_sql(old_name):
    return [
        "UPDATE attraction\n"
        "SET is_active = FALSE\n"
        f"WHERE attraction_name = {escape_sql(old_name)};"
    ]


def main():
    api_attractions = load_json(API_DATA_PATH)
    compare_report = load_json(COMPARE_REPORT_PATH)
    mapping = load_json(MAPPING_PATH)

    api_by_name = build_api_by_name(api_attractions)

    sql_lines = [
        "-- Generated by scripts/generate_attraction_update_sql.py",
        "-- Review before running on dev or EC2 database.",
        "",
    ]

    sql_lines.extend(["-- matched", ""])
    matched_names = compare_report.get("matched_names", [])

    for name in matched_names:
        api_attraction = api_by_name.get(name)

        if not api_attraction:
            print(f"Warning: API attraction not found: {name}")
            continue

        # if UPDATE_RULES["matched"]["description"]:
        #     sql_lines.extend(
        #         generate_attraction_update_sql(
        #             old_name=name,
        #             new_name=name,
        #             api_attraction=api_attraction,
        #             update_rule=UPDATE_RULES["matched"],
        #         )
        #     )

        if UPDATE_RULES["matched"]["images"]:
            sql_lines.extend(generate_image_update_sql(name, api_attraction))

        sql_lines.append("")
    
    sql_lines.extend(["-- rename_and_update", ""])
    rename_and_update = mapping.get("rename_and_update", {})
    for old_name, new_name in rename_and_update.items():
        api_attraction = api_by_name.get(new_name)

        if not api_attraction:
            print(f"Warning: API attraction not found: {new_name}")
            continue
        
        if UPDATE_RULES["rename_and_update"]["name"] or UPDATE_RULES["rename_and_update"]["description"]:
            sql_lines.extend(
                generate_attraction_update_sql(
                    old_name=old_name,
                    new_name=new_name,
                    api_attraction=api_attraction,
                    update_rule=UPDATE_RULES["rename_and_update"],
                )
            )

        if UPDATE_RULES["rename_and_update"]["images"]:
            sql_lines.extend(generate_image_update_sql(new_name, api_attraction))

        # sql_lines.extend(generate_rename_update_sql(old_name, new_name, api_attraction))
        sql_lines.append("")

    sql_lines.extend(["-- replaced_by_other_attraction", ""])
    replaced = mapping.get("replaced_by_other_attraction", {})
    for old_name in replaced.keys():
        sql_lines.extend(generate_deactivate_sql(old_name))
        sql_lines.append("")

    sql_lines.extend(["-- removed", ""])
    removed = mapping.get("removed", [])
    for old_name in removed:
        sql_lines.extend(generate_deactivate_sql(old_name))
        sql_lines.append("")

    # Only deactivate old attractions here.
    # Split attraction INSERT SQL is generated separately.
    sql_lines.extend(["-- split", ""])
    split = mapping.get("split", {})
    for old_name in split.keys():
        sql_lines.extend(generate_deactivate_sql(old_name))
        sql_lines.append("")

    OUTPUT_SQL_PATH.parent.mkdir(parents=True, exist_ok=True)

    with OUTPUT_SQL_PATH.open("w", encoding="utf-8") as file:
        file.write("\n".join(sql_lines))

    print(f"SQL generated: {OUTPUT_SQL_PATH}")


if __name__ == "__main__":
    main()